name: 'Initialize third party config'
description: 'Fetch third party configs then generate accessor classes'

runs:
  using: 'composite'
  steps:
    - name: 'Initialize third party configs'
      shell: sh
      run: |
        touch .third_party_configs
        echo $ANDROID_APP_NAME >> .third_party_configs
        cat .third_party_configs
        dart run build_runner build --delete-conflicting-outputs