name: deployments
on:
  push:
    branches: [main, staging, dev]

jobs:
  deployDev:
    name: 'Deploy to dev environment'
    if: github.event.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2
        with:
          envkey_ANDROID_APP_NAME: ${{ secrets.ANDROID_APP_NAME }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.10.4'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
      - uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: build/app/outputs/flutter-apk/app-release.apk

  deployProd:
    name: 'Deploy to production environment'
    if: github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_ANDROID_APP_NAME: ${{ secrets.ANDROID_APP_NAME }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.10.4'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
      - uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: build/app/outputs/flutter-apk/app-release.apk