name: deployments
on:
  push:
    branches: [main, staging, dev]

env:
  ANDROID_APP_NAME: ${{ secrets.ANDROID_APP_NAME }}
  ANDROID_API_KEY: ${{ secrets.ANDROID_API_KEY }}
  ANDROID_APP_ID: ${{ secrets.ANDROID_APP_ID }}
  ANDROID_MESSAGING_SENDER_ID: ${{ secrets.ANDROID_MESSAGING_SENDER_ID }}
  ANDROID_PROJECT_ID: ${{ secrets.ANDROID_PROJECT_ID }}
  ANDROID_STORAGE_BUCKET: ${{ secrets.ANDROID_STORAGE_BUCKET }}
  IOS_APP_NAME: ${{ secrets.IOS_APP_NAME }}
  IOS_API_KEY: ${{ secrets.IOS_API_KEY }}
  IOS_APP_ID: ${{ secrets.IOS_APP_ID }}
  IOS_MESSAGING_SENDER_ID: ${{ secrets.IOS_MESSAGING_SENDER_ID }}
  IOS_PROJECT_ID: ${{ secrets.IOS_PROJECT_ID }}
  IOS_STORAGE_BUCKET: ${{ secrets.IOS_STORAGE_BUCKET }}
  IOS_BUNDLE_ID: ${{ secrets.IOS_BUNDLE_ID }}

jobs:
  deployDev:
    name: 'Deploy to dev environment'
    if: github.event.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.10.4'
      - name: "Initialize third party config"
        uses: ./.github/actions/init-third-party-configs
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
      - uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: build/app/outputs/flutter-apk/app-release.apk

  deployProd:
    name: 'Deploy to production environment'
    if: github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.10.4'
      - name: "Initialize third party config"
        uses: ./.github/actions/init-third-party-configs
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
      - uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: build/app/outputs/flutter-apk/app-release.apk